#!/bin/bash

zig build vemod || exit $?

benchmark() {
	if ! which hyperfine >/dev/null; then
		echo "Please install hyperfine"
		exit 1
	fi

	prog="${1}"

	if [ -z "${prog}" ]; then exit 0; fi

	echo "Running benchmarks on '${prog}'"

	benchmarks=("zig-out/bin/vemod -j full 'comparisons/${prog}.vmd'")

	if which luajit >/dev/null; then
		benchmarks[${#benchmarks[@]}]="luajit 'comparisons/${prog}.lua'"
	fi

	if which pypy >/dev/null; then
		benchmarks[${#benchmarks[@]}]="pypy 'comparisons/${prog}.py'"
	fi

	hyperfine --warmup 5 "${benchmarks[@]}"
}

for p in $(basename -s .vmd comparisons/*.vmd); do
	benchmark "${p}"
done
