#!/bin/bash

dbgjit="${DBGJIT:-start}"
filename=""
silence=""
jitflag="-j full"

usage() {
	echo "usage: ${0} [-b <break-instructions>] <script-file>"
	exit 1
}

while [ ! x"${1}" = x"" ]; do
	case "${1}" in
	-b)
		shift
		if [ x"${1}" = "" ]; then usage; fi
		dbgjit="${1}"
		;;
	-i)
		jitflag="-j auto"
		;;
	-s)
		silence="-ex 'tty /dev/null'"
		;;
	*)
		if [ ! x"${filename}" = x"" ]; then usage; fi
		filename="${1}"
		;;
	esac
	shift
done

if [ x"${filename}" = x"" ]; then usage; fi

DBGJIT="${DBGJIT}${DBGJIT:+,}${dbgjit}"
export DBGJIT

exec /bin/sh -c "zig build vemod && gdb -q --tui ${silence} -ex 'layout asm' -ex 'layout regs' -ex 'r' --args zig-out/bin/vemod ${jitflag} \"${filename}\""
