// BNF

<curly-open> ::= "{"
<curly-close> ::= "}"

<parentheses-open> ::= "("
<parentheses-close> ::= ")"

<var-name> ::=
<integer> ::=
<float> ::=
<string> ::=

<expression> ::= 
<decleration> ::=
<loop> ::= <while>
<statement> ::= <chain> | <if> | <decleration>
<statements> ::= <statement> | <statement> <statements>


<chain> ::= 
  "chain" <curly-open>
    <statements> 
  <curly-close>

<if> ::= 
  "if" <parentheses-open> <boolean-expression> <parentheses-close> <curly-open>
    <statements> 
  <curly-close>

<while> ::= 
  "while" <parentheses-open> <boolean-expression> <parentheses-close> <curly-open>
    <statements> 
  <curly-close>

<for-header> ::= <var-decleration> ";" <boolean-expression> ";" <var-assignment>

<for> ::= 
  "for" <parentheses-open> <for-header> <parentheses-close> <curly-open>
    <statements> 
  <curly-close>


<var-decleration> ::= <var-name> ":=" <expression> ";"

