[language-server.vmdls]
command = "vmdls"

[[language]]
name = "Melancolang"
scope = "source.mcl"
roots = []
language-id = "mcl"
file-types = ["mcl"]
language-servers = ["vmdls"]

[[language]]
name = "VeMod"
scope = "source.vmd"
roots = []
comment-token = "#"
language-id = "vmd"
file-types = ["vmd"]
language-servers = ["vmdls"]
