[language-server.vmdls]
command = "vmdls"

[[language]]
name = "Melancolang"
scope = "source.mcl"
roots = []
language-id = "melancolang"
file-types = ["mcl"]
language-servers = ["vmdls"]

[[language]]
name = "VeMod"
scope = "source.vmd"
roots = []
comment-token = "#"
language-id = "vemod"
file-types = ["vmd"]
language-servers = ["vmdls"]

[[language]]
name = "Blue"
scope = "source.blue"
roots = []
language-id = "blue"
file-types = ["blue"]
language-servers = ["vmdls"]
