name: Build VS Code Extension

on:
  push:
    branches: [ "main" ]
    paths:
      - editor/vscode/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: editor/vscode
          sparse-checkout-cone-mode: false
      - name: Move editor/vscode to root
        run: |
          shopt -s dotglob
          mv editor/vscode/* .
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-vemod
          path: vscode-vemod-*.vsix
